name: News Auto Poster

on:
  schedule:
    - cron: '0 6 * * *'   # 06:00 UTC
    - cron: '0 14 * * *'  # 14:00 UTC
    - cron: '0 22 * * *'  # 22:00 UTC
  workflow_dispatch:

jobs:
  run-posting-bots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tweepy

      - name: Run Facebook script (fb.py)
        run: python fb.py

      - name: Run Twitter script (fs.py)
        run: python fs.py
